# Generated by Django 3.2.3 on 2022-02-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_book', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('availability', models.BooleanField()),
                ('group', models.CharField(choices=[('Детская книга', 'Детская книга'), ('Юмор', 'Юмор'), ('Документальная литература', 'Документальная литература'), ('Хобби', 'Хобби'), ('Роман', 'Роман'), ('Деловая литература', 'Деловая литература'), ('Учебная книга', 'Учебная книга'), ('Фантастика', 'Фантастика'), ('Детектив', 'Детектив'), ('Приключения', 'Приключения'), ('Фольклор', 'Фольклор'), ('Поэзия', 'Поэзия'), ('Религиозная литература', 'Религиозная литература'), ('Книги о психологии', 'Книги о психологии'), ('Зарубежная', 'Зарубежная'), ('Техника', 'Техника'), ('Справочная книга', 'Справочная книга'), ('Научная книга', 'Научная книга')], default='Детектив', max_length=100)),
                ('img', models.ImageField(default='Books_Shop_Site/no_image.jpg', upload_to='Books_Shop_Site/product_image')),
            ],
        ),
    ]
